[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[features]
default = ["extra", "crawler"]
extra = [
    "dep:scraper",
    "dep:serde_json",
    "dep:percent-encoding",
    "dep:flate2",
    "dep:reqwest",
]
crawler = [
    "extra",
    "dep:tokio",
    "dep:futures",
    "dep:chrono",
    "dep:htmd",
    "dep:schemars",
    "dep:markup5ever_rcdom",
]


[dependencies]
clap = { version = "4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }

toml = "*"
url = { version = "2", features = ["serde"] }

log = "*"
annotate-snippets = "0.12"

scraper = { version = "0.27", optional = true }
reqwest = { version = "0.13", default-features = false, optional = true, features = [
    "blocking",
    "json",
    "rustls",
    "gzip",
    "zstd",
] }

serde_json = { version = "1", optional = true }
percent-encoding = { version = "2", optional = true }
flate2 = { version = "1", default-features = false, optional = true, features = [
    "zlib-rs",
] }

chrono = { version = "0.4", optional = true }
futures = { version = "*", optional = true }
tokio = { version = "1", optional = true, features = ["macros", "rt-multi-thread"] }
htmd = { version = "0.5", optional = true }
markup5ever_rcdom = { version = "*", optional = true }
schemars = { version = "1", optional = true, features = ["url2"] }

[dev-dependencies]

[profile.release]
opt-level = "z"
strip = true
lto = true
codegen-units = 1
panic = "abort"
